dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decidecidavid
  strategy: git
  secure: ybC+ZjRNSV7KQumnfTyZjxIzXPm6CBbm3c/FRvXWnYfh/s82HS7cTkkkeH3TM6i0SEPPaXFYbua5fOwKLeU+iFrl8SxWgKygsRz1JTowC1XLSFA16DBYUbqkUZSiWPyQWb83aqPjgzm1AWLZasK8wQ0gn5AuwvURsjqYIHaW3V0zdGHiiRqeuxN2bNVy8nO5tNXXFQynP337w7XuBbEvzXeMPb6dVKj+rLUJTz9CUCdaFNtjYNQJ7ahT6M+2u/UlezEhGlikJrN0WumNI6QXxOh2njYzCkaki0WcywVj8hbmbaFaDKgNY0WdPm8FFa0tf3vLdiK1xInl9k0pVDZ5RqT92awhuxpk4B2kS6Nud6EpSjnV1rGC/B6km1Mduu+uMyxwFx18rHDfn6yFM98sDsXs9WEJsqh+571XtYnso9AFOU2gNlvDnFSbLtKJhodOiqgPa9xo62SRGzRRxMWuPcGAoD26FbxLay3/Z7mLXR1Zc2IHY0QM3/f9smKea7BfZQRUJg8xXduhfVSAVgrLLBpDq0DWVgj7hCDnASE4TDjpmJ0XIkN1HrXuB1zO57lzrHX7RNwMsFtUmj+q8ENdfvgcALOTP3cXPkehUF9MFJ2WnbbqDtmGag1j7O79S/Fkf6cxlA03QhLRw+Rq4Qhd0IhqbwBJrkAO5JS2SyY+7rM=
