dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decidecidavid
  strategy: git
  api_key:
    secure: VHv+fBrWBALaSCPX65yhBBsF/HPC3w+qY5cuHmWm/hQmUBhiY7dFPDxMUqXDnXx4qa65SyXOKMcl4REgYhFnVCRMypibGNCCK7hAVrYGS/D/Ith7/UfXmtAy5favKLv1FsjBdUlkwRFPJXoQZXAh4tB0nxxOLoDIdHhkE3bxsK578/UoGaDAm4BwsM8Gg0acrBnNNpElgTM2bLIOLvhYibu/kChB/+/zGo4R7XVUca56IUw2LhrixTBmyuhIc88EflxQ36/7fX4XF/lJeXSC+ihH8e7y7lwtvpTxJuAc6MQm6CS1qxGF1TkhHwW+t03ahD2sY8kZod887kpdqO+djgU3cJYP7zPldPSd5+uAqViq5hsJld5/+8hXG2CSxWWFHoZkiTozTJYEw7hZuIvwtkz/gNXtVb9KqFz8RC79XKaU29yoFNyIuNvPQTVX34kSi+3YBJmiSC1/aIa2WPyNxJ3KRWrjRh54vdWbCPc1+IQK8T8aJZJOtieeBwi/EEiS/WAH5y/Q7kxwTeuAphfAP2frwJ9fA5rbvmKcDxnKZZjUS4hlrWKcJhQeqdI6OhMV6oHqNPppy0/tkgzipVmyma6qBveIzhAe4cUamKxcI8tK5wT15uit6hFuScZZf7Si0AEzIQ3N1KROVUcUbo1eIMAFLaEtwm9oU1kyjD3S+6Y=
